<?php

use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customer = [
            ['firstname'=>'Петър','lastname'=>'Хаджипанайотов','city'=>'Хасково'],
            ['firstname'=>'Михайл','lastname'=>'Далемски','city'=>'София'],
            ['firstname'=>'Дентален','lastname'=>'Център - София','city'=>'София'],
            ['firstname'=>'Галя','lastname'=>'Стайкова','city'=>'Пазарджик'],
            ['firstname'=>'Екатерина','lastname'=>'Прова','city'=>'Пещера'],
            ['firstname'=>'Янко','lastname'=>'Стаматов','city'=>'Ивайловград'],
            ['firstname'=>'Панайот','lastname'=>'Ботушаров','city'=>'Пловдив'],
            ['firstname'=>'Христина','lastname'=>'Лалабонова','city'=>'Пловдив'],
            ['firstname'=>'Мария','lastname'=>'Каймаканска','city'=>'Кюстендил'],
            ['firstname'=>'Тодор','lastname'=>'Вълчанов','city'=>'Русе'],
            ['firstname'=>'Младен','lastname'=>'Пачеджиев','city'=>'Слащен'],
            ['firstname'=>'Красимира','lastname'=>'Терзийска','city'=>'Пазарджик'],
            ['firstname'=>'Георги','lastname'=>'Скорбански','city'=>'София'],
            ['firstname'=>'Ирина','lastname'=>'Видкова','city'=>'София'],
            ['firstname'=>'Таня','lastname'=>'Маринова','city'=>'Пирдоп'],
            ['firstname'=>'Имад','lastname'=>'Абужамус','city'=>'Казанлък'],
            ['firstname'=>'Румен','lastname'=>'Астарджиев','city'=>'София'],
            ['firstname'=>'Еди','lastname'=>'Хугасян','city'=>'Пазарджик'],
            ['firstname'=>'Евгени','lastname'=>'Попов','city'=>'Труд'],
            ['firstname'=>'ЦДМ','lastname'=>'Русе','city'=>'Русе'],
            ['firstname'=>'Клиника','lastname'=>'Дукови','city'=>'Русе'],
            ['firstname'=>'Свослава','lastname'=>'Фъртунова','city'=>'Варна'],
            ['firstname'=>'Мехмед','lastname'=>'Имам','city'=>'Крумовград'],
            ['firstname'=>'Милко','lastname'=>'Мизинов','city'=>'Пловдив'],
            ['firstname'=>'Камен','lastname'=>'Васкоев','city'=>'София'],
            ['firstname'=>'Николай','lastname'=>'Христозов','city'=>'Кирково'],
            ['firstname'=>'Христо','lastname'=>'Карастоянов','city'=>'София'],
            ['firstname'=>'Десислава','lastname'=>'Моше','city'=>'Пловдив'],
            ['firstname'=>'Илина','lastname'=>'Прова','city'=>'Варна'],
            ['firstname'=>'МАТИ','lastname'=>'МАТИ','city'=>'Пловдив'],
            ['firstname'=>'Даниела','lastname'=>'Кунева','city'=>'Варна'],
            ['firstname'=>'Дафинка','lastname'=>'Кирова','city'=>'Бургас'],
            ['firstname'=>'Фортуна','lastname'=>'Фортуна','city'=>'Варна'],
            ['firstname'=>'Иванка','lastname'=>'Камбурова','city'=>'Батак'],
            ['firstname'=>'Натали','lastname'=>'Натали','city'=>'Плевен'],
            ['firstname'=>'Таня','lastname'=>'Недкова','city'=>'София'],
            ['firstname'=>'Ана','lastname'=>'Недялкова','city'=>'Варна'],
            ['firstname'=>'Георги','lastname'=>'Бозалиев','city'=>'Пловдив'],
            ['firstname'=>'Цветозар','lastname'=>'Киьов','city'=>'Добрич'],
            ['firstname'=>'Ирена','lastname'=>'Узунова','city'=>'Добрич'],
            ['firstname'=>'Антонина','lastname'=>'Стоилова','city'=>'Варна'],
            ['firstname'=>'Пламен','lastname'=>'Хаджиев','city'=>'София'],
            ['firstname'=>'Христина','lastname'=>'Чепилова','city'=>'София'],
            ['firstname'=>'Живко','lastname'=>'Карабонев','city'=>'Хасково'],
            ['firstname'=>'Илиян','lastname'=>'Раев','city'=>'Стара Загора'],
            ['firstname'=>'Георги','lastname'=>'Къртев','city'=>'Пловдив'],
            ['firstname'=>'Георги','lastname'=>'Илиев','city'=>'Мездра'],
            ['firstname'=>'Анатолий','lastname'=>'Караманов','city'=>'Варна'],
            ['firstname'=>'МДЦ','lastname'=>'АМА','city'=>'София'],
            ['firstname'=>'Мария','lastname'=>'Тенчева','city'=>'Сливен'],
            ['firstname'=>'Румяна','lastname'=>'Прова','city'=>'София'],
            ['firstname'=>'Мила','lastname'=>'Илиева','city'=>'Стара Загора'],
            ['firstname'=>'Галина','lastname'=>'Станева','city'=>'Казанлък'],
            ['firstname'=>'Росица','lastname'=>'Кискинова','city'=>'Варна'],
            ['firstname'=>'Милен','lastname'=>'Иванов','city'=>'Велико Търново'],
            ['firstname'=>'Калин','lastname'=>'Стоянов','city'=>'София'],
            ['firstname'=>'Бойков','lastname'=>'Димитриевич','city'=>'Равда'],
            ['firstname'=>'Росица','lastname'=>'Йонкова','city'=>'Варна'],
            ['firstname'=>'Георги','lastname'=>'Карачанов','city'=>'Пловдив'],
            ['firstname'=>'Иван','lastname'=>'Хърльов','city'=>'Якоруда'],
            ['firstname'=>'Михайл','lastname'=>'Далемски','city'=>'София'],
            ['firstname'=>'Петър','lastname'=>'Димитров','city'=>'Велико Търново'],
            ['firstname'=>'Дияна','lastname'=>'Бушкалова','city'=>'Стара Загора'],
            ['firstname'=>'Мутлу','lastname'=>'Сюлейман','city'=>'Карлово'],
            ['firstname'=>'Идент','lastname'=>'Антонова','city'=>'Варна'],
            ['firstname'=>'Даниела','lastname'=>'Якимова','city'=>'Варна'],
            ['firstname'=>'Юлия','lastname'=>'Тодорова','city'=>'Варна'],
            ['firstname'=>'Дора','lastname'=>'Аргирова','city'=>'Варна'],
            ['firstname'=>'Николина','lastname'=>'камбурова','city'=>'Варна'],
            ['firstname'=>'Николай','lastname'=>'Навкиришки','city'=>'Варна'],
            ['firstname'=>'Татяна','lastname'=>'Ивакова','city'=>'Варна'],
            ['firstname'=>'ГППМПДМ','lastname'=>'„Дентсмайл“','city'=>'Варна'],
            ['firstname'=>'АИППИПД','lastname'=>'Симеонова','city'=>'Варна'],
            ['firstname'=>'Сюзан','lastname'=>'Адемова','city'=>'София'],
            ['firstname'=>'ИППИПДМ','lastname'=>'Денков','city'=>'Варна'],
            ['firstname'=>'Боряна','lastname'=>'Дякова','city'=>'Балчик'],
            ['firstname'=>'Марян','lastname'=>'Пешкирски','city'=>'София'],
            ['firstname'=>'Панчо','lastname'=>'Бътовски','city'=>'Панагюрище'],
            ['firstname'=>'Георги','lastname'=>'Урумов','city'=>'Сандански'],
            ['firstname'=>'Минка','lastname'=>'Генова','city'=>'Стара Загора'],
            ['firstname'=>'Илияна','lastname'=>'Карачанова','city'=>'Разлог'],
            ['firstname'=>'Юлия','lastname'=>'Дент','city'=>'София'],
            ['firstname'=>'Кичка','lastname'=>'Тонева','city'=>'София'],
            ['firstname'=>'Кирил','lastname'=>'Стайков','city'=>'Варна'],
            ['firstname'=>'Йонка','lastname'=>'Попова','city'=>'Пловдив'],
            ['firstname'=>'Стоян','lastname'=>'Пашкулов','city'=>'Пловдив'],
            ['firstname'=>'Стефча','lastname'=>'Чавдарова','city'=>'септември'],
            ['firstname'=>'Свлин','lastname'=>'Йорданов','city'=>'Бургас'],
            ['firstname'=>'Дияна','lastname'=>'Бушкалова','city'=>'Стара Загора'],
            ['firstname'=>'Евелин','lastname'=>'Атанасов','city'=>'Варна'],
            ['firstname'=>'Георги','lastname'=>'Ангелов','city'=>'София'],
            ['firstname'=>'Деница','lastname'=>'Статева','city'=>'София'],
            ['firstname'=>'Пенка','lastname'=>'Томова','city'=>'Пещера'],
            ['firstname'=>'Димитър','lastname'=>'Динев','city'=>'Варна'],
            ['firstname'=>'Теодора','lastname'=>'Плачкова','city'=>''],
            ['firstname'=>'Румяна','lastname'=>'Петрова','city'=>'София'],
            ['firstname'=>'Мариус','lastname'=>'Захариев','city'=>'Бяла, Русе, '],
            ['firstname'=>'Росица','lastname'=>'Колева','city'=>'Русе'],
            ['firstname'=>'Цветозар','lastname'=>'Кисьов','city'=>'Добрич'],
            ['firstname'=>'Димитър','lastname'=>'Динев','city'=>'Варна'],
            ['firstname'=>'Стефан','lastname'=>'Стефанов','city'=>'Варна'],
            ['firstname'=>'Мартин','lastname'=>'Тодоринов','city'=>'София'],
            ['firstname'=>'Мирослава','lastname'=>'Тарълова-','city'=>'София'],
            ['firstname'=>'Йонка','lastname'=>'Попова','city'=>'Пловдив'],
            ['firstname'=>'Юлия','lastname'=>'Христова','city'=>'Варна'],
            ['firstname'=>'Фатме','lastname'=>'Топова','city'=>'Ихтиман'],
            ['firstname'=>'Димитър','lastname'=>'Стаматов','city'=>'Ивайловград'],
            ['firstname'=>'МЦ','lastname'=>'Медика','city'=>'Албена'],
            ['firstname'=>'Николай','lastname'=>'Алипиев','city'=>'София'],
            ['firstname'=>'Николай','lastname'=>'Чакъров','city'=>'Стара Загора'],
            ['firstname'=>'Рилко','lastname'=>'Дачин','city'=>'София'],
            ['firstname'=>'Илина','lastname'=>'Стамова','city'=>'Стара Загора'],
            ['firstname'=>'Иван','lastname'=>'Зигов','city'=>'Бургас'],
            ['firstname'=>'Илин','lastname'=>'Дюрхан','city'=>'Варна'],
            ['firstname'=>'Галя','lastname'=>'Митова','city'=>'София'],
            ['firstname'=>'МБАЛ','lastname'=>'„Пловдив“','city'=>'Пловдив'],
            ['firstname'=>'Еди','lastname'=>'Хугасян','city'=>'Пазарджик'],
            ['firstname'=>'Минка','lastname'=>'Полякова','city'=>'София'],
            ['firstname'=>'Димитрии','lastname'=>'Малев','city'=>'Пловдив'],
            ['firstname'=>'Валентина','lastname'=>'Илиева','city'=>'София'],
            ['firstname'=>'Катя','lastname'=>'Кинова','city'=>'Русе'],
            ['firstname'=>'Величка','lastname'=>'Топузлиева','city'=>'Смолян'],
            ['firstname'=>'Веселина','lastname'=>'Панайотова','city'=>'Стара Загора'],
            ['firstname'=>'Вивадент','lastname'=>'АГППДП','city'=>'София'],
            ['firstname'=>'Клиника','lastname'=>'Пансанус','city'=>'София'],
            ['firstname'=>'ОВК','lastname'=>'Комерс','city'=>'Варна'],
            ['firstname'=>'Васил','lastname'=>'Мънков','city'=>'София'],
            ['firstname'=>'Биляна','lastname'=>'Драгиева','city'=>'София'],
            ['firstname'=>'Анатолий','lastname'=>'Соколов','city'=>'Смолян'],
            ['firstname'=>'Галя','lastname'=>'Полякова','city'=>'Козлодуй'],
            ['firstname'=>'Пенка','lastname'=>'Обрешкова','city'=>'Бургас'],
            ['firstname'=>'Здравка','lastname'=>'Вълчева','city'=>'Пазарджик'],
            ['firstname'=>'Гергана','lastname'=>'Палчева','city'=>'София'],
            ['firstname'=>'Вана','lastname'=>'Кавръкова','city'=>'Сливен'],
            ['firstname'=>'Ива','lastname'=>'Такева','city'=>'Раковски'],
            ['firstname'=>'Дженерали','lastname'=>'Закрила','city'=>'София'],
            ['firstname'=>'Бизов','lastname'=>'Бултехномед','city'=>'Пловдив'],
            ['firstname'=>'АИППМДМ','lastname'=>'„ШеринДент“','city'=>'Кърджали'],
            ['firstname'=>'Радостин','lastname'=>'Узунов','city'=>'София'],
            ['firstname'=>'Николай','lastname'=>'Колев','city'=>'Варна'],
            ['firstname'=>'Иван','lastname'=>'Кониев','city'=>'Варна'],
            ['firstname'=>'Станчева','lastname'=>'Платникова','city'=>'Варна'],
            ['firstname'=>'Виктор','lastname'=>'Хаджигаев','city'=>'Пловдив'],
            ['firstname'=>'Стела','lastname'=>'Тифчева','city'=>'София'],
            ['firstname'=>'Адриян','lastname'=>'Манолов','city'=>'София'],
            ['firstname'=>'Мария','lastname'=>'Николова','city'=>'София'],
            ['firstname'=>'Ивелина','lastname'=>'Петрова','city'=>'Русе'],
            ['firstname'=>'Георги','lastname'=>'Райков','city'=>'София'],
            ['firstname'=>'Ваня','lastname'=>'Кавлакова','city'=>'Пловдив'],
            ['firstname'=>'Стамов','lastname'=>'Стамова','city'=>'София'],
            ['firstname'=>'Мартин','lastname'=>'Божилов','city'=>'София'],
            ['firstname'=>'Дентапротект','lastname'=>'ЕООД','city'=>'Варна'],
            ['firstname'=>'Евита','lastname'=>'ЕООД','city'=>'Перник'],
            ['firstname'=>'Неделчо','lastname'=>'Танев','city'=>'Пловдив'],
            ['firstname'=>'Смайл','lastname'=>'Арт','city'=>'Варна'],
            ['firstname'=>'Светла','lastname'=>'Петрова','city'=>'Пловдив'],
            ['firstname'=>'Демирова','lastname'=>'Демирова','city'=>'Варна'],
            ['firstname'=>'Мутлу','lastname'=>'Мутлу','city'=>'Хасково'],
            ['firstname'=>'Емануйл','lastname'=>'Иванов','city'=>'Асеновград'],
            ['firstname'=>'АГППДП','lastname'=>'Нордента','city'=>'Варна'],
            ['firstname'=>'Махмуд','lastname'=>'Магамес','city'=>'Варна'],
            ['firstname'=>'Милена','lastname'=>'Бакиш','city'=>'Пловдив'],
            ['firstname'=>'Александър','lastname'=>'Вълев','city'=>'София'],
            ['firstname'=>'Мария','lastname'=>'Пенчева','city'=>'София'],
            ['firstname'=>'Николай','lastname'=>'Начев','city'=>'София'],
            ['firstname'=>'Ангел','lastname'=>'Георгиев','city'=>'Асеновград'],
            ['firstname'=>'Мартин','lastname'=>'Пров','city'=>'Варна'],
            ['firstname'=>'Венка','lastname'=>'Читалова','city'=>'Варна'],
            ['firstname'=>'Георги','lastname'=>'Антикаджиев','city'=>'София'],
            ['firstname'=>'Дамян','lastname'=>'Стойков','city'=>'София'],
            ['firstname'=>'Абдулах','lastname'=>'Сюлейман','city'=>'София'],
            ['firstname'=>'Жеко','lastname'=>'Савов','city'=>'Чирпан'],
            ['firstname'=>'Тодор','lastname'=>'Недков','city'=>'София'],
            ['firstname'=>'Легеартис','lastname'=>'ООД','city'=>'Варна'],
            ['firstname'=>'Нушка','lastname'=>'Пачеджиева','city'=>'Гоце Делчев'],
            ['firstname'=>'Иван','lastname'=>'Костов','city'=>'Несебър'],
            ['firstname'=>'Георги','lastname'=>'Томов','city'=>'Пещера'],


        ];

        foreach ($customer as $item) {
            \Illuminate\Support\Facades\DB::table('customers')->insert($item);
        }
    }
}
